### ISSUE TITLE
How to update/rescan an index

### ISSUE THREAD

**Issue by LaraSQP** [Ben136KBC/CodeXCavator2#2]
Fantastic work.

As the question says, how do I update/rescan an existing index?

Much appreciated.

**Comment by Ben136KBC** [comment]
Hi,

Inside CodeXCavator2 view near the top left to the right of the "Index:' text, there is a little blue icon with two arrows. Click it to update the existing index. You can also run CodeXCavator.Indexer.exe from the installation directory to update an index.



Ben van der Merwe - Senior Staff Consultant
KBC (A Yokogawa Company)
T: +1 403 930 5934 | F: +1 281 616 0900
W: www.kbc.global<http://www.kbc.global> | E: Ben.vanderMerwe@kbc.global<mailto:Ben.vanderMerwe@kbc.global>

**Comment by LaraSQP** [comment]
Found it. I did not expect the index refresh to be in the **Finder**. Makes sense now.

Thank you for the quick reply.

Speaking of the **Finder**, it fails topen at times. The error (bug?) seems to come from the constructor of the `MainWindow` where the bounds are restored so I have commented out that code and all is fine now:

            // Refresh restore bounds from previous window opening - crashes at times so commented out
            //IsolatedStorageFile storage = IsolatedStorageFile.GetUserStoreForAssembly();
            //try
            //{
            //    using (IsolatedStorageFileStream stream = new IsolatedStorageFileStream(windowLocationFilename, FileMode.Open, storage))
            //    using (StreamReader reader = new StreamReader(stream))
            //    {

            //        // Read restore bounds value from file
            //        Rect restoreBounds = Rect.Parse(reader.ReadLine());
            //        this.Left = restoreBounds.Left;
            //        this.Top = restoreBounds.Top;
            //        this.Width = restoreBounds.Width;
            //        this.Height = restoreBounds.Height;
            //    }
            //}
            //catch (FileNotFoundException /*ex*/)
            //{
            //    // Handle when file is not found in isolated storage, which is when:
            //    // * This is first application session
            //    // * The file has been deleted
            //}
